project_name: speechly
before:
  hooks:
  - make clean build
builds:
- binary: speechly
  goarch:
  - amd64
  goos:
  - windows
  - linux
  - darwin
  env:
  - CGO_ENABLED=0

archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
brews:
- name: speechly
  tap:
    owner: speechly
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: "https://www.speechly.com/"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
scoop:
  bucket:
    owner: speechly
    name: scoop-bucket
    token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
  homepage: "https://www.speechly.com/"
  license: MIT
