project_name: speechly
before:
  hooks:
  - make clean build
builds:
- binary: speechly
  goarch:
  - amd64
  goos:
  - windows
  - linux
  - darwin
  env:
  - CGO_ENABLED=0

archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
