# This file was generated by GoReleaser. DO NOT EDIT.
class Speechly < Formula
  desc ""
  homepage "https://www.speechly.com/"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/speechly/cli/releases/download/v0.0.1/speechly_0.0.1_macOS_x86_64.tar.gz"
    sha256 "6c7ec9d73f14e651d4ef4b9f798d5ed5c9c67b992ff96cb423612e3e35193eba"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/speechly/cli/releases/download/v0.0.1/speechly_0.0.1_Linux_x86_64.tar.gz"
      sha256 "ca524b4ac2ace5ccf0fa9f5819063ab1ec623f88edbde51bfc319973d5e1d549"
    end
  end

  def install
    bin.install "speechly"
  end
end
