name: Run unit tests
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: build
        run: make build
      - name: prepare config
        run: bin/speechly config add --apikey APIKEY --name default --skip-online-validation
      - name: Test
        run: make test
